import copy  # Needed if the config itself uses copy internally

# Default configuration dictionary for all BWR plots
DEFAULT_BWR_CONFIG = {
    "general": {
        # Figure size and style
        "width": 1920,
        "height": 1080,
        "template": "plotly_white",
    },
    "colors": {
        "background_color": "#1A1A1A",
        "primary": "#5637cd",  # Kept for clarity, used for bar_default/hbar_positive
        "bar_default": "#5637cd",
        "hbar_positive": "#5637cd",
        "hbar_negative": "#EF798A",
        "default_palette": [
            "#5637cd",
            "#779BE7",
            "#8F7BE1",
            "#EF798A",
            "#C0B9D8",
            "#8a7cff",
            "#F3A712",
            "#9f95c6",
            "#d62728",
            "#9467bd",
            "#8c564b",
            "#e377c2",
            "#7f7f7f",
            "#bcbd22",
            "#17becf",
        ],
        # Removed: secondary, tertiary, accent1, accent2, neutral1, neutral2, dark1, dark2, highlight, subtitle, gridline, axis_line, zeroline, spike_line, table_header_fill, table_header_font, table_cell_line, table_cell_fill_even, table_cell_fill_odd, brand_primary, brand_secondary, brand_text, bg_color, grid_color, title_color, subtitle_color, axis_color, annotation_color, plot_line1-10, plot_fill1-10
    },
    "fonts": {
        "normal_family": "Maison Neue, Inter, sans-serif",
        "bold_family": "Maison Neue Medium, Inter, sans-serif",
        "title": {"size": 51.6, "color": "#ededed"},
        "subtitle": {"size": 21.6, "color": "#adb0b5"},
        "axis_title": {"size": 16.8, "color": "#ededed"},
        "tick": {"size": 21.6, "color": "#ededed"},
        "legend": {"size": 24.0, "color": "#ededed"},
        "annotation": {"size": 17.4, "color": "#9f95c6"},
        # Removed: hbar_text, table_header, table_cell, family, source, watermark
    },
    "watermark": {
        "default_path": "brand-assets/bwr_white.svg",
        "default_use": True,
        "chart_opacity": 1,
        "chart_layer": "above",
        "table_x": 0.0,
        "table_y": 0.2,
        "table_sizex": 0.3,
        "table_sizey": 0.3,
        "table_opacity": 1.0,
        "table_layer": "above",
        "table_xanchor": "left",
        "table_yanchor": "top",
        # Use the final (non-duplicate) chart_* values
        "chart_x": 0.98,
        "chart_y": 0.02,
        "chart_sizex": 0.12,
        "chart_sizey": 0.12,
        "chart_xanchor": "right",
        "chart_yanchor": "bottom",
        # Removed: duplicate chart_* keys, default_type, default_text, default_image_path
    },
    "layout": {
        "margin_l": 120,
        "margin_r": 70,
        "margin_t_base": 108,
        "margin_b_min": 24,
        "plot_area_b_padding": -36,
        "title_x": 0.035,
        "title_padding": 100,
        "hovermode": "x unified",
        "hoverdistance": 100,
        "spikedistance": 1000,
    },
    "legend": {
        "bgcolor": "rgba(255, 255, 255, 0)",
        "bordercolor": "rgba(255, 255, 255, 0)",
        "borderwidth": 0,
        "font_family": "Maison Neue",
        "font_color": "#282829",
        "font_size": 14.4,
        "orientation": "h",
        "yanchor": "top",
        "y": -0.08,
        "xanchor": "left",
        "x": 0.0,
        "title": "",
        "itemsizing": "trace",
        "itemwidth": 36,
        "marker_symbol": "circle",
        "marker_size": 12,
        "traceorder": "reversed",
    },
    "annotations": {
        "default_source_y": -0.10,
        "default_source_x": 1.002,
        "xanchor": "right",
        "yanchor": "top",
        "showarrow": False,
        "chart_source_x": 0.0,
        "chart_source_y": 0.0,
        "chart_source_xanchor": "left",
        "chart_source_yanchor": "top",
    },
    "axes": {
        "linecolor": "#E9EAEB",
        "tickcolor": "#d1d5db",
        "gridcolor": "#2a2a2a",
        "showgrid_x": False,
        "showgrid_y": True,
        "ticks": "outside",
        "tickwidth": 1.2,
        "showline": True,
        "linewidth": 1.8,
        "zeroline": True,
        "zerolinewidth": 1.8,
        "zerolinecolor": "#adb0b5",
        "showspikes": True,
        "spikethickness": 2.4,
        "spikedash": "dot",
        "spikecolor": "#adb0b5",
        "spikemode": "across",
        "x_title_text": "",
        "x_ticklen": 6,
        "x_nticks": 15,
        "x_tickformat": "%d %b %y",
        "y_primary_title_text": "",
        "y_primary_tickformat": ",d",
        "y_primary_ticksuffix": "",
        "y_primary_tickprefix": "",
        "y_primary_range": None,
        "y_secondary_title_text": "",
        "y_secondary_tickformat": ",d",
        "y_secondary_ticksuffix": "",
        "y_secondary_tickprefix": "",
        "y_secondary_range": None,
        "gridwidth": 1.8,
        "y_showgrid": True,
        "y_gridcolor": "#404040",
        "x_gridcolor": "#404040",
        "titlefont_size": 14.4,
        "titlefont_color": "#adb0b5",
    },
    "plot_specific": {
        "scatter": {
            "line_width": 4.2,
            "mode": "lines",
            "default_fill_mode": None,
            "default_fill_color": None,
            "line_shape": "spline",
            "line_smoothing": 0.3,
        },
        "metric_share_area": {
            "stackgroup": "one",
            "y_tickformat": ".0%",
            "y_range": [0, 1],
            "legend_marker_symbol": "circle",
            # Removed: mode, fill, hover_template (overridden in code)
        },
        "bar": {
            "bargap": 0.15,
            # Removed: default_group_days (not referenced)
        },
        "horizontal_bar": {
            "orientation": "h",
            "textposition": "outside",
            "default_y_column": "category",
            "default_x_column": "value",
            "default_sort_ascending": False,
            "bar_height": 0.7,
            "bargap": 0.15,
            "yaxis_automargin": True,
            # Removed: xaxis_ticksuffix_auto, uniformtext_mode, uniformtext_minsize (not referenced)
        },
        "multi_bar": {
            "default_scale_values": True,
            "default_show_bar_values": False,
            "default_tick_frequency": 1,
            "barmode": "group",
            "bargap": 0.15,
            "bargroupgap": 0.1,
            "orientation": "v",
            "textposition": "outside",
            "legend_marker_symbol": "circle",
            # Removed: default_group_days (not referenced)
        },
        "stacked_bar": {
            "default_sort_descending": False,
            "barmode": "stack",
            "bargap": 0.15,
            "bargroupgap": 0.1,
            "default_scale_values": True,
            "y_tickformat": ",.0f",
            "legend_marker_symbol": "circle",
            # Removed: default_group_days (not referenced)
        },
    },
}
# Note: Output images are saved to './output/' by default if save_path is not provided in plotting methods.

def get_default_config():
    """Returns a deep copy of the default configuration"""
    return copy.deepcopy(DEFAULT_BWR_CONFIG)
