import copy  # Needed if the config itself uses copy internally

# Default configuration dictionary for all BWR plots
DEFAULT_BWR_CONFIG = {
    "general": {
        # Figure size and style
        "width": 1920,
        "height": 1080,
        "template": "plotly_white",
    },
    "colors": {
        # Moved background_color here
        "background_color": "#1A1A1A",
        # Brand Palette
        "primary": "#5637cd",
        "secondary": "#5b35d6",
        "tertiary": "#8a7cff",
        "accent1": "#EF798A",
        "accent2": "#C0B9D8",
        "neutral1": "#EFEEF0",
        "neutral2": "#adb0b5",
        "dark1": "#120b2c",
        "dark2": "#0a0a0a",
        "highlight": "#F3A712",
        "subtitle": "#adb0b5",
        # Chart Specific Defaults
        "bar_default": "#5637cd",
        "hbar_positive": "#5637cd",
        "hbar_negative": "#EF798A",
        "gridline": "#252424",
        "axis_line": "#d1d5db",
        "zeroline": "#d1d5db",
        "spike_line": "#adb0b5",
        "table_header_fill": "#5637cd",
        "table_header_font": "white",
        "table_cell_line": "rgba(0,0,0,0.2)",
        "table_cell_fill_even": "rgba(200, 200, 200, 0.6)",
        "table_cell_fill_odd": "white",
        # Default Palette
        "default_palette": [
            "#5637cd",
            "#779BE7",
            "#8F7BE1",
            "#EF798A",
            "#C0B9D8",
            "#8a7cff",
            "#F3A712",
            "#9f95c6",
            "#d62728",
            "#9467bd",
            "#8c564b",
            "#e377c2",
            "#7f7f7f",
            "#bcbd22",
            "#17becf",
        ],
    },
    "fonts": {
        # Font families and sizes for all text elements
        # NOTE: Maison Neue and Inter should be installed on your system for best appearance
        "normal_family": "Maison Neue, Inter, sans-serif",
        "bold_family": "Maison Neue Medium, Inter, sans-serif",
        "title": {"size": 51.6, "color": "#ededed"},
        "subtitle": {"size": 21.6, "color": "#adb0b5"},
        "axis_title": {"size": 16.8, "color": "#ededed"},
        "tick": {"size": 21.6, "color": "#ededed"},
        "legend": {"size": 24.0, "color": "#ededed"},
        "annotation": {"size": 17.4, "color": "#9f95c6"},
        "hbar_text": {"size": 14.4, "color": "#ededed"},
        "table_header": {"size": 19.2, "color": "white"},
        "table_cell": {"size": 16.8, "color": "#120B2C"},
    },
    "watermark": {
        # Watermark configuration
        "default_path": "brand-assets/bwr_white.svg",  # Path to watermark SVG, relative to project root
        "default_use": True,
        "chart_x": 1.012,
        "chart_xanchor": "right",
        "chart_y": 1.275,
        "chart_sizex": 0.20,
        "chart_sizey": 0.20,
        "chart_opacity": 1,
        "chart_layer": "above",
        "table_x": 0.0,
        "table_y": 0.2,
        "table_sizex": 0.3,
        "table_sizey": 0.3,
        "table_opacity": 1.0,
        "table_layer": "above",
        "table_xanchor": "left",
        "table_yanchor": "top",
        "chart_yanchor": "top",
    },
    "layout": {
        "margin_l": 120,
        "margin_r": 70,
        "margin_t_base": 108,
        "margin_b_min": 24,
        "plot_area_b_padding": -36,
        "title_x": 0.035,
        "title_padding": 100,
        "hovermode": "x unified",
        "hoverdistance": 100,
        "spikedistance": 1000,
    },
    "legend": {
        "bgcolor": "rgba(255, 255, 255, 0)",
        "bordercolor": "rgba(255, 255, 255, 0)",
        "borderwidth": 0,
        "font_family": "Maison Neue",
        "font_color": "#282829",
        "font_size": 14.4,
        "orientation": "h",
        "yanchor": "top",
        "y": -0.08,
        "xanchor": "left",
        "x": 0.0,
        "title": "",
        "itemsizing": "trace",
        "itemwidth": 36,
        "marker_symbol": "circle",
        "marker_size": 12,
        "traceorder": "reversed",
    },
    "annotations": {
        "default_source_y": -0.10,
        "default_source_x": 1.002,
        "xanchor": "right",
        "yanchor": "top",
        "showarrow": False,
        "table_source_x": 0.95,
        "table_source_y": 0.1,
        "table_xanchor": "right",
        "table_yanchor": "top",
    },
    "axes": {
        "linecolor": "#E9EAEB",
        "tickcolor": "#d1d5db",
        "gridcolor": "#2a2a2a",
        "showgrid_x": False,
        "showgrid_y": True,
        "ticks": "outside",
        "tickwidth": 1.2,
        "showline": True,
        "linewidth": 1.8,
        "zeroline": True,
        "zerolinewidth": 1.8,
        "zerolinecolor": "#adb0b5",
        "showspikes": True,
        "spikethickness": 2.4,
        "spikedash": "dot",
        "spikecolor": "#adb0b5",
        "spikemode": "across",
        "x_title_text": "",
        "x_ticklen": 6,
        "x_nticks": 15,
        "x_tickformat": "%d %b %y",
        "y_primary_title_text": "",
        "y_primary_tickformat": ",d",
        "y_primary_ticksuffix": "",
        "y_primary_tickprefix": "",
        "y_primary_range": None,
        "y_secondary_title_text": "",
        "y_secondary_tickformat": ",d",
        "y_secondary_ticksuffix": "",
        "y_secondary_tickprefix": "",
        "y_secondary_range": None,
        "gridwidth": 1.8,
        "y_showgrid": True,
        "y_gridcolor": "#404040",
        "x_gridcolor": "#404040",
        "titlefont_size": 14.4,
        "titlefont_color": "#adb0b5",
    },
    "plot_specific": {
        "scatter": {
            "line_width": 4.2,
            "mode": "lines",
            "default_fill_mode": None,
            "default_fill_color": None,
            "line_shape": "spline",
            "line_smoothing": 0.3,
        },
        "metric_share_area": {
            "mode": "none",
            "stackgroup": "one",
            "fill": "tonexty",
            "hover_template": "%{y:.1%}<extra>%{fullData.name}</extra>",
            "y_tickformat": ".0%",
            "y_range": [0, 1],
            "legend_marker_symbol": "circle",
        },
        "bar": {
            "bargap": 0.15,
            "default_group_days": None,
        },
        "horizontal_bar": {
            "orientation": "h",
            "textposition": "outside",
            "default_y_column": "category",
            "default_x_column": "value",
            "default_sort_ascending": False,
            "bar_height": 0.7,
            "bargap": 0.15,
            "xaxis_ticksuffix_auto": True,
            "yaxis_automargin": True,
            "uniformtext_mode": "hide",
            "uniformtext_minsize": 14.4,
        },
        "multi_bar": {
            "default_scale_values": True,
            "default_show_bar_values": False,
            "default_tick_frequency": 1,
            "barmode": "group",
            "bargap": 0.15,
            "bargroupgap": 0.1,
            "orientation": "v",
            "textposition": "outside",
            "legend_marker_symbol": "circle",
        },
        "stacked_bar": {
            "default_sort_descending": False,
            "barmode": "stack",
            "bargap": 0.15,
            "bargroupgap": 0.1,
            "default_group_days": None,
            "default_scale_values": True,
            "y_tickformat": ",.0f",
            "legend_marker_symbol": "circle",
        },
        "table": {
            "row_height": 72,
            "header_height": 60,
            "title_height_adjust_factor": 0.5,
            "footer_height": 96,
            "buffer_height": 60,
            "header_align_first": "left",
            "header_align_other": "center",
            "cell_align_first": "left",
            "cell_align_other": "center",
            "header_line_width": 1.2,
            "cell_line_width": 1.2,
        },
    },
}
# Note: Output images are saved to './output/' by default if save_path is not provided in plotting methods.
